const SPREADSHEET_ID = process.env.SPREADSHEET_ID;
const SPREADSHEET_USER_TAB_RANGE = "Users";
const SPREADSHEET_INSTITUTE_TAB_RANGE = "Institutes";
const SPREADSHEET_WORKSHOP_TAB_RANGE = "Workshops";
const SPREADSHEET_TEMPLATES_TAB_RANGE = "Templates";
const SERVICE_ACCOUNT_SECRET_FILE = "./secrets/service-account-secret.json";

module.exports = {
  SPREADSHEET_ID,
  SPREADSHEET_USER_TAB_RANGE,
  SPREADSHEET_INSTITUTE_TAB_RANGE,
  SPREADSHEET_WORKSHOP_TAB_RANGE,
  SPREADSHEET_TEMPLATES_TAB_RANGE,
  SERVICE_ACCOUNT_SECRET_FILE,
};
